// Package benchbuild runs Frappe's own asset build for one app inside a real bench,
// so `fpm package` ships compiled JS/CSS instead of hoping a compiled_assets/
// directory was prepared by hand.
//
// It does what `bench build --app <app> --production` does, the way bench does it:
// bench's CLI has no build command of its own; it execs the bench virtualenv's
// python as `python -m frappe.utils.bench_helper frappe build ...` from
// <bench>/sites. Frappe then symlinks sites/assets/<app> to the app's public/
// directory (for every app in sites/apps.txt), runs esbuild from apps/frappe, writes
// the hashed bundles to sites/assets/<app>/dist/ — i.e. into
// apps/<app>/<app>/public/dist/ — and runs the app's own `yarn build` when it has a
// package.json with a build script (Vite/frappe-ui frontends).
//
// Frappe apps are built from inside <bench>/apps/: their frontends locate the bench
// from their own physical path (`../../../sites/common_site_config.json`), which a
// symlink into apps/ does not satisfy. So a source tree that is not already in
// apps/ is staged there as a real copy for the build, and the package is created
// from that copy.
package benchbuild

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"fpm/internal/assets"
)

// ErrBuildFailed wraps every asset build failure so a caller can tell it from a
// validation, vendoring or network failure.
var ErrBuildFailed = errors.New("asset build failed")

// Options describes one build.
type Options struct {
	// BenchPath is the bench whose frappe, node toolchain and virtualenv run the build.
	BenchPath string
	// AppName is the Frappe app module name.
	AppName string
	// SourcePath is the app checkout root, the directory containing <AppName>/.
	SourcePath string
	// Verbose passes --verbose to frappe build and streams its output to Stdout.
	Verbose bool
	// Stdout receives progress; nil means os.Stdout.
	Stdout io.Writer
}

// Result reports what the build produced.
type Result struct {
	// Bundles maps manifest keys to hashed asset paths, LTR and RTL together
	// (RTL keys carry the rtl_ prefix), as fpm install will record them.
	Bundles map[string]string
	// Output is the combined stdout/stderr of the frappe build.
	Output string
	// BuildRoot is the app checkout the build ran in and the package must be created
	// from: SourcePath when it already lives in <bench>/apps, otherwise the staged
	// copy under <bench>/apps/<app>.
	BuildRoot string
	// Cleanup removes what was staged into the bench (the copy, the apps.txt entry).
	// The caller runs it after packaging from BuildRoot. Never nil.
	Cleanup func()
}

// bundleSourceExts are the entry-point extensions esbuild.js globs for
// (`*.bundle.{js,ts,css,sass,scss,less,styl,jsx}`).
var bundleSourceExts = map[string]bool{
	".js": true, ".ts": true, ".css": true, ".sass": true, ".scss": true, ".less": true, ".styl": true, ".jsx": true,
}

// stagingExcludes are not copied into the bench: they are either regenerated by the
// build (node_modules) or irrelevant to it and large (.git).
var stagingExcludes = map[string]bool{".git": true, "node_modules": true, "__pycache__": true}

// Build runs the asset build and returns the bundles it produced. Any failure —
// an unusable bench, a build error, or a build that produced no output for an app
// that has bundle sources — is an error wrapping ErrBuildFailed. There is no
// fallback to shipping sources only: a package that claims to be installable
// offline must carry its compiled assets.
func Build(opts Options) (Result, error) {
	out := opts.Stdout
	if out == nil {
		out = os.Stdout
	}
	bench, err := filepath.Abs(opts.BenchPath)
	if err != nil {
		return Result{Cleanup: func() {}}, err
	}
	source, err := filepath.Abs(opts.SourcePath)
	if err != nil {
		return Result{Cleanup: func() {}}, err
	}
	if opts.AppName == "" {
		return Result{Cleanup: func() {}}, fmt.Errorf("%w: app name is required", ErrBuildFailed)
	}

	python := filepath.Join(bench, "env", "bin", "python")
	for _, required := range []string{python, filepath.Join(bench, "apps", "frappe"), filepath.Join(bench, "sites")} {
		if _, err := os.Stat(required); err != nil {
			return Result{Cleanup: func() {}}, fmt.Errorf("%w: %s is not a usable bench (%s missing)", ErrBuildFailed, bench, required)
		}
	}
	for _, tool := range []string{"node", "yarn"} {
		if _, err := exec.LookPath(tool); err != nil {
			return Result{Cleanup: func() {}}, fmt.Errorf("%w: %s is not on PATH; frappe's asset build needs node and yarn", ErrBuildFailed, tool)
		}
	}

	buildRoot, cleanupStage, err := stageAppIntoBench(bench, opts.AppName, source, out)
	if err != nil {
		return Result{Cleanup: func() {}}, err
	}
	cleanupAppsTxt, err := ensureInAppsTxt(bench, opts.AppName)
	if err != nil {
		cleanupStage()
		return Result{Cleanup: func() {}}, err
	}
	cleanup := func() { cleanupAppsTxt(); cleanupStage() }
	fail := func(output string, err error) (Result, error) {
		cleanup()
		return Result{Output: output, Cleanup: func() {}}, err
	}

	// An app with its own package.json declares npm packages its bundles import
	// (erpnext's onscan.js, say) and often a frontend `build` script. bench installs
	// them with `yarn install --check-files` in the app directory when the app is
	// added (bench/app.py install_app), and esbuild resolves them from
	// apps/<app>/node_modules; without that step the build fails on the first such
	// import. node_modules is a build-time artifact: the archive step leaves it out.
	if _, statErr := os.Stat(filepath.Join(buildRoot, "package.json")); statErr == nil {
		fmt.Fprintf(out, "Installing '%s' node dependencies (yarn install --check-files in %s)\n", opts.AppName, buildRoot)
		yarn := exec.Command("yarn", "install", "--check-files", "--non-interactive")
		yarn.Dir = buildRoot
		yarnOut, yarnErr := yarn.CombinedOutput()
		if opts.Verbose {
			out.Write(yarnOut)
		}
		if yarnErr != nil {
			return fail(string(yarnOut), fmt.Errorf("%w: yarn install for '%s' failed: %v\n%s",
				ErrBuildFailed, opts.AppName, yarnErr, strings.TrimSpace(string(yarnOut))))
		}
	}

	args := []string{"-m", "frappe.utils.bench_helper", "frappe", "build", "--app", opts.AppName, "--production"}
	if opts.Verbose {
		args = append(args, "--verbose")
	}
	fmt.Fprintf(out, "Building assets for '%s' in bench %s:\n  (cd sites && %s %s)\n",
		opts.AppName, bench, python, strings.Join(args, " "))

	cmd := exec.Command(python, args...)
	cmd.Dir = filepath.Join(bench, "sites")
	// The app is in apps/ but not pip-installed into the bench's virtualenv;
	// frappe.get_module(app) still has to import it to locate its public/ directory,
	// so put the checkout on the import path.
	pythonPath := buildRoot
	if existing := os.Getenv("PYTHONPATH"); existing != "" {
		pythonPath += string(os.PathListSeparator) + existing
	}
	cmd.Env = append(os.Environ(), "PYTHONPATH="+pythonPath)

	var buf strings.Builder
	if opts.Verbose {
		cmd.Stdout = io.MultiWriter(&buf, out)
		cmd.Stderr = io.MultiWriter(&buf, out)
	} else {
		cmd.Stdout = &buf
		cmd.Stderr = &buf
	}
	runErr := cmd.Run()
	output := buf.String()
	if runErr != nil {
		return fail(output, fmt.Errorf("%w: frappe build for '%s' exited with error: %v\n%s",
			ErrBuildFailed, opts.AppName, runErr, strings.TrimSpace(output)))
	}

	moduleDir := filepath.Join(buildRoot, opts.AppName)
	ltr, rtl, err := assets.Bundles(moduleDir, opts.AppName)
	if err != nil {
		return fail(output, fmt.Errorf("%w: %v", ErrBuildFailed, err))
	}
	bundles := make(map[string]string, len(ltr)+len(rtl))
	for k, v := range ltr {
		bundles[k] = v
	}
	for k, v := range rtl {
		bundles[k] = v
	}

	sources, err := bundleSources(moduleDir)
	if err != nil {
		return fail(output, fmt.Errorf("%w: %v", ErrBuildFailed, err))
	}
	if len(sources) > 0 && len(bundles) == 0 {
		return fail(output, fmt.Errorf("%w: '%s' declares %d bundle source(s) (%s) but the build wrote nothing to %s",
			ErrBuildFailed, opts.AppName, len(sources), strings.Join(sources, ", "),
			filepath.Join(moduleDir, "public", "dist")))
	}
	fmt.Fprintf(out, "Asset build for '%s' produced %d bundle(s).\n", opts.AppName, len(bundles))
	return Result{Bundles: bundles, Output: output, BuildRoot: buildRoot, Cleanup: cleanup}, nil
}

// stageAppIntoBench makes <bench>/apps/<app> the app checkout for the duration of the
// build. A source that already is that directory is built in place. Otherwise the
// source is copied there (minus .git, node_modules and caches), which is what a
// frontend build's `../../../sites` assumption needs; an existing, different entry is
// an error rather than something to overwrite.
func stageAppIntoBench(bench, app, source string, out io.Writer) (buildRoot string, cleanup func(), err error) {
	noop := func() {}
	target := filepath.Join(bench, "apps", app)

	resolvedTarget, targetErr := filepath.EvalSymlinks(target)
	resolvedSource, _ := filepath.EvalSymlinks(source)
	if targetErr == nil {
		if resolvedTarget == resolvedSource || resolvedTarget == source {
			return target, noop, nil
		}
		kind := "directory"
		if info, err := os.Lstat(target); err == nil && info.Mode()&os.ModeSymlink != 0 {
			kind = "symlink"
		}
		return "", noop, fmt.Errorf("%w: bench already has a %s at %s that is not this checkout (%s); "+
			"remove it or package from that bench's copy", ErrBuildFailed, kind, target, source)
	} else if info, lerr := os.Lstat(target); lerr == nil && info.Mode()&os.ModeSymlink != 0 {
		return "", noop, fmt.Errorf("%w: %s is a dangling symlink; remove it", ErrBuildFailed, target)
	}

	fmt.Fprintf(out, "Staging '%s' into %s for the build (a copy without .git and node_modules)\n", app, target)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return "", noop, fmt.Errorf("%w: %v", ErrBuildFailed, err)
	}
	if err := copyTree(source, target); err != nil {
		os.RemoveAll(target)
		return "", noop, fmt.Errorf("%w: cannot stage %s into the bench: %v", ErrBuildFailed, source, err)
	}
	return target, func() { os.RemoveAll(target) }, nil
}

// copyTree copies a source checkout, preserving symlinks and file modes and skipping
// stagingExcludes at any depth.
func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		if rel == "." {
			return os.MkdirAll(dst, 0o755)
		}
		if d.IsDir() && stagingExcludes[d.Name()] {
			return filepath.SkipDir
		}
		target := filepath.Join(dst, rel)
		info, err := d.Info()
		if err != nil {
			return err
		}
		switch {
		case d.Type()&fs.ModeSymlink != 0:
			link, err := os.Readlink(p)
			if err != nil {
				return err
			}
			return os.Symlink(link, target)
		case d.IsDir():
			return os.MkdirAll(target, info.Mode().Perm()|0o700)
		default:
			return copyFile(p, target, info.Mode().Perm())
		}
	})
}

func copyFile(src, dst string, mode fs.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	outF, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode|0o600)
	if err != nil {
		return err
	}
	if _, err := io.Copy(outF, in); err != nil {
		outF.Close()
		return err
	}
	return outF.Close()
}

// ensureInAppsTxt lists the app in sites/apps.txt for the build, because
// frappe.build.make_asset_dirs only links sites/assets/<app> for listed apps —
// and without that link the build writes into a real sites/assets/<app>/dist
// directory instead of the app's public/dist. The original file is restored.
func ensureInAppsTxt(bench, app string) (cleanup func(), err error) {
	noop := func() {}
	p := filepath.Join(bench, "sites", "apps.txt")
	original, readErr := os.ReadFile(p)
	if readErr != nil && !os.IsNotExist(readErr) {
		return noop, fmt.Errorf("%w: cannot read %s: %v", ErrBuildFailed, p, readErr)
	}
	for _, line := range strings.Split(string(original), "\n") {
		if strings.TrimSpace(line) == app {
			return noop, nil
		}
	}
	content := string(original)
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += app + "\n"
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		return noop, fmt.Errorf("%w: cannot update %s: %v", ErrBuildFailed, p, err)
	}
	return func() {
		if readErr != nil { // did not exist before
			os.Remove(p)
			return
		}
		os.WriteFile(p, original, 0o644)
	}, nil
}

// bundleSources lists the esbuild entry points under <module>/public, using the
// same glob as esbuild.js get_all_files_to_build (excluding node_modules and dist).
func bundleSources(moduleDir string) ([]string, error) {
	public := filepath.Join(moduleDir, "public")
	if info, err := os.Stat(public); err != nil || !info.IsDir() {
		return nil, nil
	}
	var found []string
	err := filepath.WalkDir(public, func(p string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			if d.Name() == "node_modules" || d.Name() == "dist" {
				return filepath.SkipDir
			}
			return nil
		}
		name := d.Name()
		ext := filepath.Ext(name)
		if !bundleSourceExts[ext] {
			return nil
		}
		if strings.HasSuffix(strings.TrimSuffix(name, ext), ".bundle") {
			rel, _ := filepath.Rel(public, p)
			found = append(found, filepath.ToSlash(rel))
		}
		return nil
	})
	return found, err
}
