package cmd

import (
	"archive/zip"
	"os"

	"fpm/internal/assetbench"
	"path/filepath"
	"testing"

	"fpm/internal/metadata"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fakeAssetBench is a bench-shaped directory holding nothing but frappe's asset
// pipeline: what internal/benchbuild needs to compile an app's bundles through node,
// with no virtualenv, no site and no database. The stand-in for node writes what
// esbuild would, but only for entry points that are actually on disk when it runs —
// which is the whole point of the test below.
func fakeAssetBench(t *testing.T, binDir, appName string) string {
	t.Helper()
	bench := t.TempDir()
	writeFile(t, filepath.Join(bench, "apps", "frappe", "esbuild", "esbuild.js"), "// frappe's pipeline")
	writeFile(t, filepath.Join(bench, "apps", "frappe", "node_modules", ".yarn-integrity"), "{}")
	writeFile(t, filepath.Join(bench, "sites", "apps.txt"), "frappe\n")

	entry := filepath.Join("apps", appName, appName, "public", "js", appName+"-highlight.bundle.js")
	script := "#!/bin/sh\n" +
		"[ -f \"$FRAPPE_BENCH_ROOT/" + entry + "\" ] || exit 0\n" +
		"out=\"$FRAPPE_BENCH_ROOT/sites/assets/" + appName + "/dist/js\"\n" +
		"mkdir -p \"$out\" || exit 1\n" +
		"echo 'console.log(1)' > \"$out/" + appName + "-highlight.bundle.ABCDEFGH.js\"\n" +
		"exit 0\n"
	require.NoError(t, os.WriteFile(filepath.Join(binDir, "node"), []byte(script), 0o755))
	return bench
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

// TestPackageCompilesBundlesTheFrontendBuildGenerates is frappe/wiki's shape, and the
// reason its packages shipped an uncompiled desk bundle.
//
// wiki's esbuild entry point is not checked in: `yarn build` writes
// wiki/public/js/wiki-highlight.bundle.js, which wiki's own .gitignore lists as build
// output. Packaging used to run frappe's esbuild before the app's own build, so the
// glob for *.bundle.* found nothing, the bundle was packaged as source, and the guard
// then refused the package with a message telling the user to package against a bench —
// which is exactly what they had done.
//
// The fake esbuild here writes its output only when the entry point exists, so this
// passes only while the app's own build runs first.
func TestPackageCompilesBundlesTheFrontendBuildGenerates(t *testing.T) {
	src := crmShapedApp(t, "wiki")
	yarnLog := fakeYarn(t, map[string]string{
		"wiki/public/frontend/index.html": spaHTML("wiki", "frontend"),
		// Written by the app's own build, exactly as wiki's build:highlight step does.
		"wiki/public/js/wiki-highlight.bundle.js": "// generated by the app build",
	})
	bench := fakeAssetBench(t, filepath.Dir(yarnLog), "wiki")

	args, outDir := packageArgs(t, src, "3.1.0", "--org", "frappe", "--bench-path", bench)
	out, err := SharedExecuteCommand(rootCmd, args...)
	require.NoError(t, err, out)

	fpmPath := filepath.Join(outDir, "wiki-3.1.0.fpm")
	meta, err := metadata.ReadMetadataFromFPMArchive(fpmPath)
	require.NoError(t, err)

	assert.True(t, meta.AssetsBuilt)
	assert.Equal(t, "/assets/wiki/dist/js/wiki-highlight.bundle.ABCDEFGH.js",
		meta.AssetBundles["wiki-highlight.bundle.js"],
		"the entry point the app's own build generated must be compiled and recorded")

	inspectFPM(t, fpmPath, func(filesInArchive map[string]*zip.File, _ *zip.ReadCloser) {
		assert.Contains(t, filesInArchive, "wiki/public/dist/js/wiki-highlight.bundle.ABCDEFGH.js",
			"the compiled desk bundle has to be in the package; shipping only the source is what made the app render nothing")
		assert.Contains(t, filesInArchive, "wiki/public/frontend/index.html", "and the SPA still ships alongside it")
	})
}

// TestPackageRefusesWhenTheBenchCompiledNothing keeps the guard honest for the case it
// could not previously describe: a bench was supplied and still produced no bundles.
// Telling that user to pass --bench-path is not a remedy.
func TestPackageRefusesWhenTheBenchCompiledNothing(t *testing.T) {
	src := crmShapedApp(t, "wiki")
	yarnLog := fakeYarn(t, map[string]string{
		"wiki/public/frontend/index.html":         spaHTML("wiki", "frontend"),
		"wiki/public/js/wiki-highlight.bundle.js": "// generated by the app build",
	})
	binDir := filepath.Dir(yarnLog)
	bench := fakeAssetBench(t, binDir, "wiki")
	// An esbuild that compiles nothing, whatever it is given.
	require.NoError(t, os.WriteFile(filepath.Join(binDir, "node"), []byte("#!/bin/sh\nexit 0\n"), 0o755))

	args, outDir := packageArgs(t, src, "3.1.0", "--org", "frappe", "--bench-path", bench)
	_, err := SharedExecuteCommand(rootCmd, args...)

	require.Error(t, err)
	assert.Contains(t, err.Error(), bench, "the error has to name the bench that produced nothing")
	assert.NotContains(t, err.Error(), "packaging against a bench (--bench-path <bench>)",
		"do not tell someone who passed --bench-path to pass --bench-path")
	assert.NoFileExists(t, filepath.Join(outDir, "wiki-3.1.0.fpm"))
}

// TestPackageExplainsHowToCompileWithoutABench: with no bench to hand, the way out is
// to let fpm fetch frappe's pipeline, which is what --no-bench-scaffold turns off.
func TestPackageExplainsHowToCompileWithoutABench(t *testing.T) {
	src := SharedCreateMinimalAppForPackage(t, t.TempDir(), "webshop", map[string]string{
		"webshop/public/web.bundle.js": "// esbuild entry point",
	})

	args, _ := packageArgs(t, src, "1.0.0", "--org", "frappe")
	_, err := SharedExecuteCommand(rootCmd, args...)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "--no-bench-scaffold")
	assert.Contains(t, err.Error(), "--bench-path")
}

// TestPackageBuildsSiblingDependentAppsInsideTheBench is helpdesk's shape: its
// desk/package.json declares `"@framework/ui": "link:../../frappe/ui"`, which yarn
// resolves relative to the package declaring it — so the checkout has to sit at
// <bench>/apps/<app> with frappe beside it or the install fails before the build runs.
//
// The fake build here writes its output only when it can see that sibling, so this
// passes only while `fpm package` stages into the bench before building the frontend.
func TestPackageBuildsSiblingDependentAppsInsideTheBench(t *testing.T) {
	src := crmShapedApp(t, "helpdesk")
	// Declare the sibling the way helpdesk does, in the project that is built.
	writeFile(t, filepath.Join(src, "package.json"), `{
	  "private": true,
	  "name": "helpdesk",
	  "dependencies": {"@framework/ui": "link:../../frappe/ui"},
	  "scripts": {"build": "cd frontend && yarn build"}
	}`)

	binDir := t.TempDir()
	logPath := filepath.Join(binDir, "invocations.log")
	// ../frappe/ui from <bench>/apps/helpdesk is <bench>/apps/frappe/ui.
	script := "#!/bin/sh\n" +
		"echo \"$@\" >> \"" + logPath + "\"\n" +
		"case \"$1\" in install|ci) exit 0 ;; esac\n" +
		"[ -d \"$PWD/../frappe/ui\" ] || exit 0\n" +
		"mkdir -p \"$PWD/helpdesk/public/frontend\"\n" +
		"printf '%s' '" + spaHTML("helpdesk", "frontend") + "' > \"$PWD/helpdesk/public/frontend/index.html\"\n" +
		"exit 0\n"
	require.NoError(t, os.WriteFile(filepath.Join(binDir, "yarn"), []byte(script), 0o755))
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))

	bench := fakeAssetBench(t, binDir, "helpdesk")
	writeFile(t, filepath.Join(bench, "apps", "frappe", "ui", "package.json"), `{"name":"frappe-ui"}`)

	args, outDir := packageArgs(t, src, "1.0.0", "--org", "frappe", "--bench-path", bench)
	out, err := SharedExecuteCommand(rootCmd, args...)
	require.NoError(t, err, out)

	fpmPath := filepath.Join(outDir, "helpdesk-1.0.0.fpm")
	inspectFPM(t, fpmPath, func(filesInArchive map[string]*zip.File, _ *zip.ReadCloser) {
		assert.Contains(t, filesInArchive, "helpdesk/public/frontend/index.html",
			"the frontend build has to run where the sibling app resolves, i.e. inside the bench")
	})
}

// TestFrappeRefFollowsTheAppsReleaseLine: frappe's apps mirror its release-line
// branches, and compiling a version-15 app's desk bundles with version-16's esbuild is a
// mismatch that installs cleanly and misbehaves later. An explicit --frappe-ref always
// wins; a ref that is not a release line has no reliable mapping and keeps the default.
func TestFrappeRefFollowsTheAppsReleaseLine(t *testing.T) {
	cases := []struct {
		name     string
		gitRef   string
		explicit string
		want     string
	}{
		{"release line is followed", "version-15", "", "version-15"},
		{"another release line", "version-14", "", "version-14"},
		{"explicit flag wins", "version-15", "version-16", "version-16"},
		{"a tag has no mapping", "v3.1.0", "", assetbench.DefaultFrappeRef},
		{"develop has no mapping", "develop", "", assetbench.DefaultFrappeRef},
		{"no ref at all", "", "", assetbench.DefaultFrappeRef},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			resetPackageCmdFlags()
			t.Cleanup(resetPackageCmdFlags)
			if tc.explicit != "" {
				require.NoError(t, packageCmd.Flags().Set("frappe-ref", tc.explicit))
			}
			assert.Equal(t, tc.want, frappeRefForApp(packageCmd, tc.gitRef))
		})
	}
}

// TestPackageUsesTheBenchTheCheckoutAlreadyLivesIn is the shape every `fpm mirror`
// checkout has: the workspace is laid out as a bench and each app is cloned to
// <bench>/apps/<slug>. Such a tree must compile its desk bundles using the bench it is
// already in, without --bench-path and without fetching a second frappe — otherwise a
// catalogue run would pull frappe once per app into a directory its cache does not even
// keep.
//
// --no-bench-scaffold is what makes the assertion sharp: it forbids fetching, so the
// build can only succeed by using the enclosing bench.
func TestPackageUsesTheBenchTheCheckoutAlreadyLivesIn(t *testing.T) {
	binDir := t.TempDir()
	bench := fakeAssetBench(t, binDir, "wiki")
	writeFile(t, filepath.Join(bench, "sites", "common_site_config.json"), `{"socketio_port": 9000}`)

	// The app is cloned into the bench, exactly as the mirror's workspace does it.
	src := filepath.Join(bench, "apps", "wiki")
	writeFile(t, filepath.Join(src, "wiki", "hooks.py"), `app_name = "wiki"`)
	writeFile(t, filepath.Join(src, "wiki", "__init__.py"), `__version__ = "3.1.0"`)
	writeFile(t, filepath.Join(src, "wiki", "modules.txt"), "Wiki\n")
	writeFile(t, filepath.Join(src, "wiki", "patches.txt"), "")
	writeFile(t, filepath.Join(src, "wiki", "public", "js", "wiki-highlight.bundle.js"), "// entry point")

	require.NoError(t, os.WriteFile(filepath.Join(binDir, "yarn"), []byte("#!/bin/sh\nexit 0\n"), 0o755))
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))

	args, outDir := packageArgs(t, src, "3.1.0", "--org", "frappe")
	out, err := SharedExecuteCommand(rootCmd, args...)
	require.NoError(t, err, out)

	assert.NotContains(t, out, "Fetching frappe's asset pipeline",
		"a checkout already inside a bench must not fetch a second frappe")

	meta, err := metadata.ReadMetadataFromFPMArchive(filepath.Join(outDir, "wiki-3.1.0.fpm"))
	require.NoError(t, err)
	assert.Equal(t, "/assets/wiki/dist/js/wiki-highlight.bundle.ABCDEFGH.js",
		meta.AssetBundles["wiki-highlight.bundle.js"],
		"the enclosing bench has to have compiled the bundle")
}
